#dynamo DB table
NotesTable:
  Type: AWS::DynamoDB::Table
  Properties:
    TableName: NotesTable
    BillingMode: PAY_PER_REQUEST
    AttributeDefinitions: 
      - AttributeName: notesId
        AttributeType: S
    KeySchema: 
      - AttributeName: notesId
        KeyType: HASH
    TableName: NotesTableDB

#user pool
CognitoUserPool:
  Type: AWS::Cognito::UserPool
  Properties:
    UserPoolName: NotesUserPool

#userpool webclient
CognitoUserPoolWebClient:
  Type: AWS::Cognito::UserPoolClient
  Properties:
    UserPoolId: !Ref CognitoUserPool
    ClientName: web

#userpool domain
CognitoUserPoolDomain:
  Type: AWS::Cognito::UserPoolDomain
  Properties: 
    UserPoolId: !Ref CognitoUserPool
    Domain: mynotesappdemocd
    